name: 'Toolbox with tooltip'
multiple: TRUE
category: 'Toolbox'
enabled: TRUE
fields:
  idIcon:
    type: vactory_icon_picker
    label: "Icon"
    options:
      '#required': TRUE
  link:
    type: url_extended
    label: 'Lien'
  label:
    type: text
    label: 'text du lien pour mobile'
  active_button:
    type: checkbox
    label: 'Afficher Avec style button'


