name: "Footer variant 4"
multiple: TRUE
category: "Layout"
enabled: TRUE
fields:
  cta_social:
    type: url_extended
    label: "Social media links"
  icon:
    type: vactory_icon_picker
    label: "Icon"
extra_fields:
  enableThemeSwitcher:
    type: checkbox
    label: "Activer Dark Mode"
  logo:
    type: image
    label: Footer's logo
  use_menu:
    type: text
    label: "Menu Main ID"
    options:
      "#description": "Menu machine name. Default to main"
  copyrights:
    type: text
    label: "copyrights Text"
  signateur:
    type: text_format
    label: 'Page signateur, ex: "Agence digitale VOID"'
    options:
      "#format": full_html
  under_footer:
    type: text_format
    label: "Footer bottom paragraph"
    options:
      "#format": full_html
