name: 'DF: Toolbox contact'
multiple: TRUE
category: 'Toolbox'
enabled: TRUE
fields:
  icon:
    type: vactory_icon_picker
    label: "Icon"
    options:
      '#required': TRUE
  link:
    type: url_extended
    label: 'Link'
  description:
    type: text
    label: 'Description'
extra_fields:
  mode:
    type: checkbox
    label: 'Toolbox with descriptions'
