name: "Footer variant 2"
multiple: TRUE
category: "Layout"
enabled: TRUE
fields:
  cta_social:
    type: url_extended
    label: "Social media links"
  icon:
    type: vactory_icon_picker
    label: "Icon"
extra_fields:
  enableThemeSwitcher:
    type: checkbox
    label: "Activer Dark Mode"
  use_footer_main:
    type: text
    label: "Footer Main Menu ID"
    options:
      "#description": "Footer Main Machine Menu. Default to Footer"
  use_footer_bottom:
    type: text
    label: "Footer Bottom Menu"
    options:
      "#description": "Footer Bottom Machine name."
  logo:
    type: image
    label: Footer's logo
  followUsText:
    type: text
    label: "Follow us text"
  copyrights:
    type: text
    label: "copyrights text"
  signateur:
    type: text_format
    label: 'Page signateur, ex: "Agence digitale VOID"'
    options:
      "#format": full_html
